### ISSUE TITLE
question for “for_chrono_view_embedding” 

### ISSUE THREAD

**Issue by HuTaoMylove** [Jho-Yonsei/SMURF#1]
thank you for your work and open source.
with torch1.13.1,torchdiffeq 0.2.4,I copy the code in for_chrono_view_embedding to conda torchdiffeq,and I got this 

from .odeint import odeint, odeint_dense, odeint_event
ImportError: cannot import name 'odeint_dense' from 'torchdiffeq._impl.odeint' 

Could you give me some suggestion? tks!

**Comment by xiaoyaolovlife** [comment]
![image](https://github.com/user-attachments/assets/4348918b-bdef-42a5-b04b-6de9cb668b69)
Hello, may I ask if you have successfully reproduced the results of this paper? I encountered the same problem and couldn't reproduce the results with the original code provided by the authors. I'm quite confused about this work—what happens if the two variables decoded by the Decoder are all same? I faced this issue while writing my own code for reproduction. Thank you.
